/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checa a app e a conexao com o banco */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cuisine-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os tipos de culinaria */
        get: operations["CuisineTypeController_findAll"];
        put?: never;
        /** Cria um tipo de culinaria */
        post: operations["CuisineTypeController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cuisine-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CuisineTypeController_findOne"];
        put?: never;
        post?: never;
        delete: operations["CuisineTypeController_remove"];
        options?: never;
        head?: never;
        patch: operations["CuisineTypeController_update"];
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as tags */
        get: operations["TagController_findAll"];
        put?: never;
        /** Cria uma tag */
        post: operations["TagController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TagController_findOne"];
        put?: never;
        post?: never;
        delete: operations["TagController_remove"];
        options?: never;
        head?: never;
        patch: operations["TagController_update"];
        trace?: never;
    };
    "/restaurants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista restaurantes com resumo de visitas */
        get: operations["RestaurantController_findAll"];
        put?: never;
        /** Cadastra um restaurante */
        post: operations["RestaurantController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/suggestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sugere onde comer
         * @description Aplica os filtros e devolve uma lista curta ordenada por uma heuristica (nota, se voltaria, prioridade de desejo e tempo desde a ultima visita), ou sorteia entre os candidatos quando strategy=RANDOM.
         */
        get: operations["RestaurantController_suggest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalha um restaurante, com o historico de visitas */
        get: operations["RestaurantController_findOne"];
        put?: never;
        post?: never;
        delete: operations["RestaurantController_remove"];
        options?: never;
        head?: never;
        /**
         * Atualiza um restaurante
         * @description Inclui o veredito `wouldReturn`, que antes nao tinha rota de escrita.
         */
        patch: operations["RestaurantController_update"];
        trace?: never;
    };
    "/restaurants/{restaurantId}/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as visitas de um restaurante */
        get: operations["VisitController_findAllByRestaurant"];
        put?: never;
        /** Registra uma visita com nota */
        post: operations["VisitController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/{restaurantId}/visits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VisitController_findOne"];
        put?: never;
        post?: never;
        delete: operations["VisitController_remove"];
        options?: never;
        head?: never;
        patch: operations["VisitController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateCuisineTypeDto: {
            /** @example Japonesa */
            name: string;
        };
        UpdateCuisineTypeDto: {
            /** @example Japonesa */
            name?: string;
        };
        CreateTagDto: {
            /**
             * @description Caracteristica livre do lugar (romantico, pet friendly, ...)
             * @example romantico
             */
            name: string;
        };
        UpdateTagDto: {
            /**
             * @description Caracteristica livre do lugar (romantico, pet friendly, ...)
             * @example romantico
             */
            name?: string;
        };
        CreateRestaurantDto: {
            /** @example Cantina do Bairro */
            name: string;
            /** @description Um lugar pode ter mais de uma culinaria (ex.: japonesa e peruana). */
            cuisineTypeIds: string[];
            tagIds?: string[];
            /** @enum {string} */
            priceRange?: "CHEAP" | "MODERATE" | "EXPENSIVE" | "FINE_DINING";
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "ARCHIVED";
            /**
             * @description Quanto voces querem ir. Alimenta o endpoint de sugestao.
             * @default NORMAL
             * @enum {string}
             */
            wishlistPriority: "LOW" | "NORMAL" | "HIGH";
            address?: string;
            neighborhood?: string;
            city?: string;
            notes?: string;
            /** @description Veredito atual. Normalmente so faz sentido depois da primeira visita. */
            wouldReturn?: boolean;
        };
        UpdateRestaurantDto: {
            /** @example Cantina do Bairro */
            name?: string;
            /** @description Um lugar pode ter mais de uma culinaria (ex.: japonesa e peruana). */
            cuisineTypeIds?: string[];
            tagIds?: string[];
            /** @enum {string} */
            priceRange?: "CHEAP" | "MODERATE" | "EXPENSIVE" | "FINE_DINING";
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "ARCHIVED";
            /**
             * @description Quanto voces querem ir. Alimenta o endpoint de sugestao.
             * @default NORMAL
             * @enum {string}
             */
            wishlistPriority: "LOW" | "NORMAL" | "HIGH";
            address?: string;
            neighborhood?: string;
            city?: string;
            notes?: string;
            /** @description Veredito atual. Normalmente so faz sentido depois da primeira visita. */
            wouldReturn?: boolean;
        };
        CreateVisitDto: {
            /**
             * Format: date-time
             * @example 2026-09-01T20:30:00.000Z
             */
            visitedAt: string;
            rating: number;
            notes?: string;
        };
        UpdateVisitDto: {
            /**
             * Format: date-time
             * @example 2026-09-01T20:30:00.000Z
             */
            visitedAt?: string;
            rating?: number;
            notes?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CuisineTypeController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CuisineTypeController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCuisineTypeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CuisineTypeController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CuisineTypeController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CuisineTypeController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCuisineTypeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTagDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RestaurantController_findAll: {
        parameters: {
            query?: {
                /** @description Busca por parte do nome (case-insensitive). */
                search?: string;
                /** @description Aceita `a,b` ou repetido. */
                cuisineTypeIds?: string[];
                tagIds?: string[];
                priceRanges?: ("CHEAP" | "MODERATE" | "EXPENSIVE" | "FINE_DINING")[];
                city?: string;
                neighborhood?: string;
                /** @description Por padrao arquivados ficam de fora. */
                status?: "ACTIVE" | "ARCHIVED";
                /** @description Somente lugares marcados como "voltaria". */
                onlyWouldReturn?: boolean;
                /** @description Somente lugares que voces ainda nao visitaram. */
                onlyNotVisited?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RestaurantController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRestaurantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RestaurantController_suggest: {
        parameters: {
            query?: {
                /** @description Busca por parte do nome (case-insensitive). */
                search?: string;
                /** @description Aceita `a,b` ou repetido. */
                cuisineTypeIds?: string[];
                tagIds?: string[];
                priceRanges?: ("CHEAP" | "MODERATE" | "EXPENSIVE" | "FINE_DINING")[];
                city?: string;
                neighborhood?: string;
                /** @description Por padrao arquivados ficam de fora. */
                status?: "ACTIVE" | "ARCHIVED";
                /** @description Somente lugares marcados como "voltaria". */
                onlyWouldReturn?: boolean;
                /** @description Somente lugares que voces ainda nao visitaram. */
                onlyNotVisited?: boolean;
                strategy?: "RANKED" | "RANDOM";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RestaurantController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RestaurantController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RestaurantController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRestaurantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VisitController_findAllByRestaurant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VisitController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVisitDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VisitController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurantId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VisitController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurantId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VisitController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurantId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVisitDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
